# Generated by Django 4.0.1 on 2022-03-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=50)),
                ('make', models.CharField(choices=[('nissan', 'NISSAN'), ('jeep', 'JEEP'), ('subaru', 'SUBARU')], default='nissan', max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.person')),
            ],
        ),
    ]
