# Generated by Django 4.0.1 on 2022-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(choices=[('motorcycle', 'MOTOR CYCLE'), ('car', 'CAR'), ('truck', 'TRUCK')], default='car', max_length=50),
        ),
    ]
