# Generated by Django 4.0.1 on 2022-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_vehicle_vehicletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='hasVehicle',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
